[WIP]reference/syntaxの日本語訳
typst-jp/typst-jp.github.io pull request #12
Opened 2024-06-22 04:11 UTC by gomazarashi

作業中です。

2024-06-23 14:34 UTC, 3w36zj6 commented on docs/reference/syntax.md
> +## モード　{#modes}
```suggestion
## モード { #modes }
```

NITS: 全角スペースが混じっているのと、id属性の指定のコードスタイルが他の見出しと異なっています。

2024-06-23 14:34 UTC, 3w36zj6 commented on docs/reference/syntax.md
IMO: コロンの`:`と`：`の表記ゆれを何らかのルールに従って統一した方が良いと思います。

FYI: ルールの一例として、例えばJTF日本語標準スタイルガイドでは以下のように示されています。

> 原則として和文ではコロン(:)を使用しません。
> 原文でコロンが使われている場合も、和文では使用しません。
> ただし和文でも、見出し語とその説明の間にコロンを使う場合があります。使用する場合は全角で表記します。

https://www.jtf.jp/tips/styleguide

2024-06-23 14:37 UTC, gomazarashi commented on docs/reference/syntax.md
> +## モード　{#modes}
すみません、ありごとうございます
反映を行いました。

2024-06-23 14:42 UTC, mkpoli commented on docs/reference/syntax.md
参照のために、ほぼ同時に[Discordにて同じDiscussion](https://discord.com/channels/1196431244158849064/1251938021314400306/1254442501171843084)を始めています。

> コロンを使うべきかどうかどう思われますか
> 
> JTF日本語標準スタイルガイド（ https://www.jtf.jp/pdf/jtf_style_guide.pdf ）では、以下のような規定があるように、私は普通の文内で、文の末尾などに見られるコロンは使わず、「（例：…）」のような場合のみ使い、全角記号に統一するのが妥当ではないかと思います
> 
> 記号 | 表記 | 例
> コロン （：）| 全角 | 日時：3月16日午後1時、例：
> 
> > 原則として和文ではコロン（：）を使用しません。原文でコロンが使われている場合
> > も、和文では使用しません。ただし和文でも、見出し語とその説明の間にコロンを使う場合
> > があります。使用する場合は全角で表記します。

2024-06-24 00:22 UTC, gomazarashi commented on docs/reference/syntax.md
ご指摘ありがとうございます。例示に用いるコロンを全角に統一し、文末に用いられているものは削除しました。

2024-06-24 00:46 UTC, gomazarashi commented
現時点ではインポートやインクルードをカタカナで表記していますが、このような単語に関して英語表記すべきか迷っているため、その方面に関してご意見いただきたいです。

2024-06-24 14:20 UTC, mkpoli commented
> 現時点ではインポートやインクルードをカタカナで表記していますが、このような単語に関して英語表記すべきか迷っているため、その方面に関してご意見いただきたいです。

_import_くらいは大体の技術ドキュメントで「インポート」とカタカナ書きなので、Typstで_import_と_include_は同じレベルの概念であるため、「インクルード」で統一したほうが（現状のままのほうが）いいかもしれません

ただし、_include_はLaTeXの文脈などで_include_のままのも多いようです。

2024-06-24 14:25 UTC, mkpoli approved these changes

2024-06-24 14:33 UTC, gomazarashi commented
ありがとうございます。現状のままにしておこうと思います。

2024-06-24 23:42 UTC, gomazarashi commented
もう数日待ってマージを行います。気になる箇所がございましたらご指摘をよろしくお願いいたします。

2024-06-25 05:19 UTC, 3w36zj6 requested changes

2024-06-25 05:19 UTC, 3w36zj6 commented on docs/reference/syntax.md
>  ## 注释 { #comments }
MUST: 原文の中国語が残ってしまっているので、翻訳が必要です。

```suggestion
## コメント { #comments }
```

2024-06-25 05:23 UTC, gomazarashi commented on docs/reference/syntax.md
>  ## 注释 { #comments }
すみません、見落としておりました 反映を行いました。

2024-06-25 06:02 UTC, 3w36zj6 approved these changes

2024-06-27 06:58 UTC, stepney141 approved these changes

2024-06-27 11:33 UTC, gomazarashi commented
レビューありがとうございました。マージを行います。

2024-06-27 11:35 UTC, merged