翻訳ガイドラインを作成
typst-jp/typst-jp.github.io pull request #18
Opened 2024-06-23 16:39 UTC by mkpoli

Closes #15, #16

2024-06-23 16:45 UTC, mkpoli commented
Based on Disscussion on Discord, the consensus are towarding not inserting half-width space (U+0020) manually.

https://discord.com/channels/1196431244158849064/1251938021314400306/1254457656500949152

2024-06-23 21:26 UTC, 3w36zj6 reviewed
LGTM: 構成は概ね良いと思います。

2024-06-23 21:26 UTC, 3w36zj6 commented on README.md
> +> For English version, please refer to [README.en.md](README.en.md).
IMO: アラート構文を使用すると読みやすくなるかもしれません。

https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

```suggestion
> [!NOTE]
> For English version, please refer to [README.en.md](README.en.md).
```

2024-06-23 21:26 UTC, 3w36zj6 commented on README.en.md
> +> 日本語版は[README.md](README.md)を参照してください。
IMO: アラート構文を使用すると読みやすくなるかもしれません。

https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

```suggestion
> [!NOTE]
> 日本語版は[README.md](README.md)を参照してください。
```

2024-06-23 21:26 UTC, 3w36zj6 commented on CONTRIBUTING.md
> +1. 翻訳は、原則説明文章や表などに限る。コードやコマンドなどの技術的な表現は、原文のままとする。
以下のsuggestionは敬体に統一するとしたときの例です。

```suggestion
1. 翻訳は、原則として説明文章や表などに限ります。コードやコマンドなどの技術的な表現は、原文のままとします。
```

2024-06-23 21:26 UTC, 3w36zj6 commented on CONTRIBUTING.md
IMO: 箇条書き内での敬体と常体の混在は避けた方が良いかもしれません。

2024-06-23 21:26 UTC, 3w36zj6 commented on CONTRIBUTING.md
> +翻訳は[Github上の当リポジトリ](https://github.com/typst-jp/typst-jp.github.io)を中心に行います。実際の翻訳作業やそれに対する議論や提案などは、主にGithubの[Issue](https://github.com/typst-jp/typst-jp.github.io/issues)や[Pull Request](https://githu
NITS: `GitHub`が正式です。

```suggestion
翻訳は[GitHub上の当リポジトリ](https://github.com/typst-jp/typst-jp.github.io)を中心に行います。実際の翻訳作業やそれに対する議論や提案などは、主にGitHubの[Issue](https://github.com/typst-jp/typst-jp.github.io/issues)や[Pull Request](https://github.com/typst-jp/typst-jp.github.io/pulls)機能を通じて行います。また、[Discordサーバー「くみはんクラブ」](https://discord.gg/9xF7k4aAuH)の`#typst-翻訳`チャンネルでも、質問の対応や合意の形成などを行うことがあります。
```

2024-06-23 21:29 UTC, 3w36zj6 commented
作業の重複を防ぐため、翻訳に着手する前にIssueでの宣言を推奨する旨の文章を追加すると良いかもしれないと思いました。

2024-06-24 07:24 UTC, stepney141 requested changes
全体的な内容は同意します。ただし、「参考」節に載せている他プロジェクトの翻訳ガイドの内容をもっと取り入れた方が良いと思います。

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +3. コロン（「：」）やセミコロン（「；」）は、「（例：）」などの場合以外、原則として使用しないこと。
```suggestion
3. コロン「：」やセミコロン「；」は、原則として文中では利用しないこと。ただし、「例：」など、文中以外で用いる場合は除く。
```

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +最終的にコンパイルされたファイルは`./dist`にあります。
```suggestion
最終的にコンパイルされたファイルは`./dist`に出力されます。
```
の方が良さそうです。

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +スタイルマニュアルでは、当プロジェクトにおける翻訳の品質確保のための、統一したスタイルの参照基準を提供します。具体的には、基本、文体、表記、用語の4つの観点から、翻訳の際に留意すべき事項を示します。
日本語では、並列する複数の単語を1つの文に併記するときは、中黒「・」を使うのが一般的です。

```suggestion
スタイルマニュアルでは、当プロジェクトにおける翻訳の品質確保のための、統一したスタイルの参照基準を提供します。具体的には、基本・文体・表記・用語の4つの観点から、翻訳の際に留意すべき事項を示します。
```

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +この基準はあくまで参照するためのもので、絶対的なスタンダードではありませんため、ケース・バイ・ケースで適用し、できれば統一性を保つようにしてください。また、執筆の妨げになる時やスタイルがわからない場合でも、無理に従う必要はなく、翻訳を続行し、訂正や議論を待つこともできます。
文章の意味がよく理解できなかったため、私の解釈で書き直しました。

```suggestion
本スタイルマニュアルは絶対的なルールではなく、翻訳全体の整合性を保つための基本方針として提供しているものです。そのため、本マニュアルの内容に必ず従う義務はなく、ケース・バイ・ケースで適用して翻訳を行ってください。本マニュアルの内容に疑問がある場合は、IssueやPull Requestなどで他の翻訳者に意見を求めることもできます。
```

IMO: 「必ず従う義務はなく、ケース・バイ・ケースで適用する」という曖昧な条件をつけると、わざわざガイドラインを作った意義が薄れてしまい、翻訳者も混乱してしまう気がします。もう少しガイドラインを強制化してもいいのではないでしょうか。

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
IMO:
- 箇条書き内での敬体と常体の混在は避けたほうが良いと思います。
- 「参考」節に載せている他プロジェクトの翻訳ガイドの内容をもっと取り入れた方が良いと思います。

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +> 当プロジェクトの[README](./README.md)や「[はじめに：Typst Japan Communityより](https://typst-jp.github.io/docs/)」、[Typst公式](https://typst.app/)の[ライセンス](https://github.com/typst/typst/blob/main/LICENSE)や[コントリビューション・
```suggestion
[!NOTE]
当プロジェクトの[README](./README.md)や「[はじめに：Typst Japan Communityより](https://typst-jp.github.io/docs/)」、[Typst公式](https://typst.app/)の[ライセンス](https://github.com/typst/typst/blob/main/LICENSE)や[コントリビューション・ガイド](https://github.com/typst/typst/blob/main/CONTRIBUTING.md)も併せてご参照ください。
```

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +1. 基本的に「です」「ます」調の敬体を使用すること。ただし、引用、見出し、箇条書きなどに関しては、その限りではありません。
```suggestion
1. 基本的に「です」「ます」調の敬体を使用すること。ただし、引用・見出し・箇条書きなどに関しては、その限りではありません。
```

2024-06-24 07:24 UTC, stepney141 commented on CONTRIBUTING.md
> +2. 柔軟に用語とそうではありませんものを考慮し、訳し分けること。
```suggestion
2. 用語と用語でないものを、柔軟に見分けて訳し分けること。
```

2024-06-24 07:24 UTC, stepney141 commented on README.en.md
> +Please refer to the [Translation Guidelines (CONTRIBUTING.md)](CONTRIBUTING.md) and create a [Pull Request](https://github.com/typst-jp/typst-jp.github.io/pulls). Questions and discussions are also w
```suggestion
Please refer to the [Translation Guidelines (CONTRIBUTING.md)](CONTRIBUTING.md) and create a [Pull Request](https://github.com/typst-jp/typst-jp.github.io/pulls). Any questions or discussions are also welcome in [Issues](https://github.com/typst-jp/typst-jp.github.io/issues).
```

2024-06-24 07:24 UTC, stepney141 commented on README.en.md
> +If you have any questions, please join the Discord server [Kumihan Club](https://discord.gg/9xF7k4aAuH) and contact us.
```suggestion
Also, feel free to join our Discord server [Kumihan Club](https://discord.gg/9xF7k4aAuH) and contact us.
```

2024-06-24 14:40 UTC, mkpoli commented
> 作業の重複を防ぐため、翻訳に着手する前にIssueでの宣言を推奨する旨の文章を追加すると良いかもしれないと思いました。

現在は小さい修正を行い、DraftPRとして作成することで、翻訳開始の宣言が行われていますが、別にIssueを立てると、やはり余計に手間がかかってしまうようです。できるだけ翻訳作業の手順を減らしたいので、一つの代替案としては、こちらでまだ翻訳されていない箇所に対して、全部のIssueを立て、そこに興味がある人は、そこでコメントするとアサインされ、作業を始めることができると思います。いかがでしょうか。

2024-06-24 14:45 UTC, mkpoli commented on CONTRIBUTING.md
体言「～すること。」や名詞列挙の場合はどう扱うべきなのかについては、ちょっと考える必要がありそうですね。

2024-06-24 14:48 UTC, mkpoli commented on CONTRIBUTING.md
> +スタイルマニュアルでは、当プロジェクトにおける翻訳の品質確保のための、統一したスタイルの参照基準を提供します。具体的には、基本、文体、表記、用語の4つの観点から、翻訳の際に留意すべき事項を示します。
それが特にカジュアルの文体で一般的であるのは存じ上げておりますが、やはり書籍などの編集では、語句の並列などで、中黒を使わないほうが推奨されているようですので、あえて中黒から読点に変えました。

![image](https://github.com/typst-jp/typst-jp.github.io/assets/3502597/561ffca3-fbce-4089-bdeb-a27e8a2c1e47)

2024-06-24 15:11 UTC, mkpoli commented on CONTRIBUTING.md
> +3. コロン（「：」）やセミコロン（「；」）は、「（例：）」などの場合以外、原則として使用しないこと。
```suggestion
3. コロン「：」やセミコロン「；」は、原則として使用しないこと。ただし、「例：」など、文中以外で用いる場合はその限りではありません。
```

2024-06-24 15:16 UTC, mkpoli commented on README.en.md
> +If you have any questions, please join the Discord server [Kumihan Club](https://discord.gg/9xF7k4aAuH) and contact us.
```suggestion
Also, feel free to join our Discord server [Kumihan Club](https://discord.gg/9xF7k4aAuH) to get in touch with us directly.
```

2024-06-24 15:18 UTC, mkpoli commented on CONTRIBUTING.md
・Further disscussion in: https://github.com/typst-jp/typst-jp.github.io/pull/18#discussion_r1651166806
・体力がなくなりましたので、取り入れてほしい内容があれば取り入れておいてくださると助かります。

2024-06-24 23:37 UTC, gomazarashi approved these changes

2024-06-24 23:40 UTC, gomazarashi commented
> 翻訳されていない箇所に対して、全部のIssueを立て、そこに興味がある人は、そこでコメントするとアサインされ、作業を始める
個人的にはその方式でよいと思います。

2024-07-02 13:47 UTC, mkpoli commented
@stepney141 さらなるフィードバック待ってます

2024-07-02 16:43 UTC, gomazarashi commented
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md
こちらで言われているような行の追加・削除に関してはどのように扱いましょうか？
(英語版ドキュメントの変更の取り込み方にもよるでしょうが...)

2024-07-02 17:06 UTC, mkpoli commented
> https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md こちらで言われているような行の追加・削除に関してはどのように扱いましょうか？ (英語版ドキュメントの変更の取り込み方にもよるでしょうが...)

できる限り変えないほうが確かに楽に差分しやすいので、そのほうが良いかもしれません。

2024-07-05 19:09 UTC, stepney141 approved these changes

2024-07-05 19:12 UTC, stepney141 commented
大変遅くなりまして申し訳ありません。とりあえずこの内容で運用してみて、問題点があればその都度直していくようにすればよいかと思います。

2024-07-05 20:40 UTC, 3w36zj6 approved these changes

2024-07-07 08:46 UTC, merged